const ERROR = 'ERROR';
const SUCCESS = 'SUCCESS';


// Success response
const CREATED = 201;
const ACCEPTED = 200;
const RESOURCE_UPDATE = 204;

// REDIRECT
const NOT_MODIFIED = 304;

// CLIENT
const BAD_REQUEST = 400;


//SERVER
const SERVICE_UNAVAILABLE = 503;
const BAD_GATEWAY = 502

module.exports = {
    ERROR, SUCCESS, NOT_MODIFIED,CREATED,
    ACCEPTED,SERVICE_UNAVAILABLE,BAD_GATEWAY,
    BAD_REQUEST, RESOURCE_UPDATE}